# Update

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Tests

    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x

        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AUDIENCE: ${{ secrets.AUDIENCE }}
          ISSUER_BASE_URL: ${{ secrets.ISSUER_BASE_URL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}

      - name: Run Tests
        run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AUDIENCE: ${{ secrets.AUDIENCE }}
          ISSUER_BASE_URL: ${{ secrets.ISSUER_BASE_URL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
